In [1]:
import numpy as np

Same size = element by element

In [42]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
c = a + b
c

array([5, 6, 7])

In [20]:
c = []
for elem_a, elem_b in zip(a, b):
    c.append(elem_a + elem_b)
c

[5, 6, 7]

By the way a + b or b + a is the same thing

Broadcasting allows these types of operatioons to be performed on arrays of different sizes, we can just add a scalar to an array

In [21]:
a + 5

# same as
a + np.array([5, 5, 5])
# (in reality the implementation doesn't dup the array though)

array([5, 6, 7])

How does this "extension" work with matrices?

In [46]:
M = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1],])
M

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
a

array([0, 1, 2])

Will it apply a to the rows or the columns?

In [48]:
M + a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

The answer is neither! It applies to the latter dimension (the last child dimension). It kinda make sense, for example in a table we want to apply an operation to every row, not a column. When we got a array of tables, we want to apply the operation to every row of those tables

M + a or a + M is same

In [49]:
a + M

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
cube = np.zeros((3, 3, 3), dtype=int)
cube

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [28]:
cube + a

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [38]:
# same as np.array([0, 1, 2])
a = np.arange(3)
a

array([0, 1, 2])

In [37]:
# same as np.array([[0],
#                   [1],
#                   [2]])

M = np.zeros((3, 1))
M

array([[0.],
       [0.],
       [0.]])

Previously we saw the case of B having less rows than A.
Now, what if B has less columns than A, but also A has less rows than B?

In [41]:
a + M

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

### Why Do Broadcasting Exists?

Broadcasting exists to apply element-wise operations. For example imagine you got a list of item and you want to discount them:


In [76]:
prices = np.array([10, 50, 100])
# Normally we would do this
# discount all prices by 10%
discounted = [p * 0.5 for p in prices]
discounted

[5.0, 25.0, 50.0]

In [79]:
# The same thing is done simply with:
np.array([10, 50, 100]) * 0.5

array([ 5., 25., 50.])

In [83]:
# What if you got more complicated discount prices then?
# Expensive items, should stay expensive even with discounts
discounts = [0.5, 0.8, 0.9]
discounted = [p * d for p, d in zip(prices, discounts)]
discounted

[5.0, 40.0, 90.0]

In [84]:
# the shortcut to do that with broadcasting is
np.array([10, 50, 100]) * np.array([0.5, 0.8, 0.9])

array([ 5., 40., 90.])

In [110]:
# now imagine we got a 2D array of product prices, and a 1D array of discounts
# for example first col are cheap products, second col another type of products, etc
prices = np.array([[10, 50, 100],
                   [20, 60, 110],
                   [30, 70, 120]])

discounts = np.array([0.5, 0.8, 0.9])


r = []
for product_type in prices:
    r.append([p * d for p, d in zip(product_type, discounts)])
np.array(r)

array([[  5.,  40.,  90.],
       [ 10.,  48.,  99.],
       [ 15.,  56., 108.]])

As we add dimension, this will become more and more tedious, but thanks to broadcasting, no matter the number of dimension we can still just do:

In [111]:
prices * discounts

array([[  5.,  40.,  90.],
       [ 10.,  48.,  99.],
       [ 15.,  56., 108.]])

And it also works of course of course with a scalar

In [115]:
prices * 0.5

array([[ 5., 25., 50.],
       [10., 30., 55.],
       [15., 35., 60.]])

We saw this case already

In [117]:
prices * [0.5, 0.8, 0.9]

array([[  5.,  40.,  90.],
       [ 10.,  48.,  99.],
       [ 15.,  56., 108.]])

This is the same but on the column dimension

In [130]:
prices = np.array([[10, 50, 100],
                   [20, 60, 110],
                   [30, 70, 120]])

prices - np.array([[10],
                   [20],
                   [30]])

array([[ 0, 40, 90],
       [ 0, 40, 90],
       [ 0, 40, 90]])

How about this?

In [118]:
prices * [0.5, 0.8]

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

It doesn't work because..., it's unclear what you are trying to do!

In [122]:
for product_type in prices:
    for p in product_type:
        # -> here how do multiplty p by the discount as they have different length
        # -> it's not that it's not possible, 
        # -> it's just that it's unclear what you want to do
        pass