In [11]:
import numpy as np

[pretty good stuff](https://www.coursera.org/learn/neural-networks-deep-learning/programming/isoAV/python-basics-with-numpy/lab?path=%2Fnotebooks%2Frelease%2FW2A1%2FPython_Basics_with_Numpy.ipynb)

### Reading A numpy array

In [22]:
# (m, n)
# (rows, columns)
x = np.random.rand(3, 1)
print("this is (3rows, 1col)\n", x, "\n")

x = np.random.rand(1, 3)
print("this is (1row, 3cols)\n", x, "\n")

# think (down, then right)
x = np.random.rand(2, 5)
print("this is (2👇, 5👉)\n", x, "\n")

# think (down, then right)
x = np.random.rand(2, 5)
print("this is (2 down, 5 to the right)\n", x, "\n")

this is (3rows, 1col)
 [[0.78436938]
 [0.48953956]
 [0.94293467]] 

this is (1row, 3cols)
 [[0.12853985 0.13496332 0.85478158]] 

this is (2👇, 5👉)
 [[0.81648584 0.91135709 0.95729418 0.4767533  0.44996772]
 [0.82237153 0.16632911 0.82893767 0.34223751 0.03992044]] 

this is (2 down, 5 to the right)
 [[0.47991905 0.3815944  0.1137041  0.78917916 0.98449819]
 [0.75141238 0.53828016 0.97326227 0.27957884 0.55484147]] 



### Axis

In [44]:
import numpy as np
x = np.array([
    [ 1,  2, 3, 4],
    [ 11,  12,  13, 14],
])
print(x, "\n")

# axis means "sum along the axis", keyword is along
# axis 0 = sum by going down
# axis 1 = sum by going to the right
print('sum by going 👇\n', x.sum(axis=0), "\n'")

print('sum by to the 👉\n', x.sum(axis=1), "\n")

[[ 1  2  3  4]
 [11 12 13 14]] 

sum by going 👇
 [12 14 16 18] 
'
sum by to the 👉
 [10 50] 



In [47]:
x = np.random.rand(4, 5)
y = np.sum(x, axis=1)
y.shape

(4,)

# Multiplications

In [87]:
A = np.ones((3, 3))

B = np.array([[5, 6],
              [7, 8],
              [7, 8]])

C = A @ B


# 1.	Matrix  A  has shape (m, n)
# 2.	Matrix  B  has shape (n, p)
# 3.    Matrix C  will have shape (m, p)

C.shape

(3, 2)